import test from 'node:test';
import assert from 'node:assert/strict';
import { TokenService } from '../server/security/token-service.js';
import { MemoryIdentityStore } from '../server/infrastructure/memory-identity-store.js';
import { AuthService } from '../server/application/auth-service.js';

const setup=()=>{const identity=new MemoryIdentityStore();const tokens=new TokenService('a'.repeat(64));return {identity,tokens,auth:new AuthService({identity,tokens})}};

test('cadastro protege senha e emite sessão curta',async()=>{const {identity,tokens,auth}=setup();const result=await auth.register({email:'Pessoa@Exemplo.com',password:'senha-muito-segura',displayName:'Pessoa'});assert.equal(result.user.email,'pessoa@exemplo.com');assert.equal(result.expiresIn,900);assert.equal(tokens.verify(result.accessToken).sub,result.user.id);assert.equal(identity.users.get(result.user.id).password,undefined);assert.notEqual(identity.users.get(result.user.id).passwordHash,'senha-muito-segura')});

test('login inválido não revela qual campo falhou',async()=>{const {auth}=setup();await assert.rejects(()=>auth.login('x@x.com','incorreta'),error=>error.code==='INVALID_CREDENTIALS'&&error.status===401)});

test('refresh é rotativo e não pode ser reutilizado',async()=>{const {auth}=setup();const registered=await auth.register({email:'a@b.com',password:'senha-muito-segura',displayName:'A'});await auth.refresh(registered.refreshToken);await assert.rejects(()=>auth.refresh(registered.refreshToken),error=>error.code==='INVALID_SESSION')});

test('RBAC segrega residências, pisos e cômodos',async()=>{const {identity,auth}=setup();const owner=(await auth.register({email:'owner@x.com',password:'senha-muito-segura',displayName:'Owner'})).user;const stranger=(await auth.register({email:'other@x.com',password:'senha-muito-segura',displayName:'Other'})).user;const home=await identity.createHome({name:'Casa',ownerId:owner.id});assert.equal(await identity.getRole(home.id,owner.id),'owner');assert.equal(await identity.getRole(home.id,stranger.id),null);const floor=await identity.createFloor({homeId:home.id,name:'Térreo',position:0});assert.ok(floor);assert.equal(await identity.createFloor({homeId:home.id,name:'térreo',position:1}),null);assert.ok(await identity.createRoom({floorId:floor.id,name:'Sala',position:0}));assert.equal(await identity.createRoom({floorId:floor.id,name:'sala',position:1}),null)});

test('recuperação usa token único e invalida sessões anteriores',async()=>{let resetUrl;const identity=new MemoryIdentityStore();const tokens=new TokenService('b'.repeat(64));const emailSender={sendPasswordReset:async message=>{resetUrl=message.url;return true}};const auth=new AuthService({identity,tokens,emailSender,appUrl:'https://ninho.example'});const registered=await auth.register({email:'reset@ninho.local',password:'senha-antiga-segura',displayName:'Reset'});await auth.requestPasswordReset('reset@ninho.local');const token=new URL(resetUrl).searchParams.get('reset');assert.ok(token);await auth.resetPassword(token,'senha-nova-bem-segura');await assert.rejects(()=>auth.refresh(registered.refreshToken),error=>error.code==='INVALID_SESSION');await assert.rejects(()=>auth.resetPassword(token,'outra-senha-bem-segura'),error=>error.code==='INVALID_RESET_TOKEN');assert.ok(await auth.login('reset@ninho.local','senha-nova-bem-segura'));});

test('solicitação não revela se o e-mail existe',async()=>{let deliveries=0;const identity=new MemoryIdentityStore();const tokens=new TokenService('c'.repeat(64));const auth=new AuthService({identity,tokens,emailSender:{sendPasswordReset:async()=>{deliveries+=1;return true}}});await auth.register({email:'known@ninho.local',password:'senha-conhecida-segura',displayName:'Known'});assert.equal(await auth.requestPasswordReset('missing@ninho.local'),undefined);assert.equal(await auth.requestPasswordReset('known@ninho.local'),undefined);assert.equal(deliveries,1);});

test('falha de entrega não altera resposta da solicitação',async()=>{const identity=new MemoryIdentityStore();const tokens=new TokenService('d'.repeat(64));const auth=new AuthService({identity,tokens,emailSender:{sendPasswordReset:async()=>{throw new Error('SMTP indisponível')}}});await auth.register({email:'smtp@ninho.local',password:'senha-smtp-segura',displayName:'SMTP'});assert.equal(await auth.requestPasswordReset('smtp@ninho.local'),undefined);assert.equal(identity.audit.at(-1).result,'delivery_unavailable');});

test('token expirado é rejeitado sem alterar senha',async()=>{let resetUrl;const identity=new MemoryIdentityStore();const tokens=new TokenService('e'.repeat(64));const auth=new AuthService({identity,tokens,emailSender:{sendPasswordReset:async message=>{resetUrl=message.url;return true}}});await auth.register({email:'expired@ninho.local',password:'senha-original-segura',displayName:'Expired'});await auth.requestPasswordReset('expired@ninho.local');identity.passwordResets.values().next().value.expiresAt=new Date(Date.now()-1000).toISOString();await assert.rejects(()=>auth.resetPassword(new URL(resetUrl).searchParams.get('reset'),'senha-que-nao-entra'),error=>error.code==='INVALID_RESET_TOKEN');assert.ok(await auth.login('expired@ninho.local','senha-original-segura'));});
