import test from 'node:test';
import assert from 'node:assert/strict';
import { EventBus } from '../server/core/event-bus.js';
import { OrchestrationService } from '../server/application/orchestration-service.js';
import { MemoryHomeRepository } from '../server/infrastructure/memory-home-repository.js';

async function setup(){
  const repository=new MemoryHomeRepository();const events=new EventBus();const service=new OrchestrationService({repository,events});const homeId='home-1';
  const light=await repository.saveDevice(homeId,{id:'light-1',name:'Luz',type:'light',online:true,power:false,capabilities:[{code:'power',writable:true}]});
  const fan=await repository.saveDevice(homeId,{id:'fan-1',name:'Ventilador',type:'plug',online:true,power:false,capabilities:[{code:'power',writable:true}]});
  return {repository,events,service,homeId,light,fan};
}

test('cena registra execução total e ignora repetição pelo executionId',async()=>{const {repository,service,homeId,light}=await setup();const scene=await service.createScene(homeId,{name:'Acender',actions:[{deviceId:light.id,controls:{power:true}}]});const first=await service.executeScene(homeId,scene.id,{executionId:'event-1'});const duplicate=await service.executeScene(homeId,scene.id,{executionId:'event-1'});assert.equal(first.status,'succeeded');assert.equal(duplicate.status,'duplicate');assert.equal((await repository.listOrchestrationExecutions(homeId)).length,1);});

test('cena registra resultado parcial quando uma ação falha',async()=>{const {repository,service,homeId,light,fan}=await setup();await repository.updateDevice(homeId,fan.id,{online:false});const scene=await service.createScene(homeId,{name:'Duas ações',actions:[{deviceId:light.id,controls:{power:true}},{deviceId:fan.id,controls:{power:true}}]});const result=await service.executeScene(homeId,scene.id,{executionId:'partial-1'});assert.equal(result.status,'partial');assert.deepEqual(result.results.map(item=>item.status),['succeeded','failed']);});

test('gatilho de dispositivo executa uma vez e respeita condição',async()=>{const {repository,service,homeId,light,fan}=await setup();const scene=await service.createScene(homeId,{name:'Ligar ventilador',actions:[{deviceId:fan.id,controls:{power:true}}]});const automation=await service.saveAutomation(homeId,{name:'Quando luz ligar',sceneId:scene.id,trigger:{type:'device_state',deviceId:light.id,field:'power',operator:'eq',value:true},conditions:[{deviceId:fan.id,field:'online',operator:'eq',value:true}]});const event={id:'device-event-1',type:'device.updated',payload:{homeId,deviceId:light.id,power:true}};const first=await service.processDeviceEvent(event);const second=await service.processDeviceEvent(event);assert.equal(first[0].status,'succeeded');assert.equal(second[0].status,'duplicate');assert.equal((await repository.findDevice(homeId,fan.id)).power,true);assert.equal((await repository.listAutomations(homeId)).find(item=>item.id===automation.id).lastExecution.status,'succeeded');});

test('motor rejeita ciclo direto e alerta conflito de ações',async()=>{const {repository,service,homeId,light,fan}=await setup();const turnsLightOff=await service.createScene(homeId,{name:'Apagar luz',actions:[{deviceId:light.id,controls:{power:false}}]});await assert.rejects(()=>service.saveAutomation(homeId,{name:'Loop',sceneId:turnsLightOff.id,trigger:{type:'device_state',deviceId:light.id,field:'power',value:true}}),error=>error.code==='AUTOMATION_LOOP_DETECTED');const fanOn=await service.createScene(homeId,{name:'Ventilador on',actions:[{deviceId:fan.id,controls:{power:true}}]});const fanOff=await service.createScene(homeId,{name:'Ventilador off',actions:[{deviceId:fan.id,controls:{power:false}}]});const trigger={type:'device_state',deviceId:light.id,field:'power',value:true};const first=await service.saveAutomation(homeId,{name:'A',sceneId:fanOn.id,trigger});const second=await service.saveAutomation(homeId,{name:'B',sceneId:fanOff.id,trigger});assert.deepEqual(second.conflicts,[first.id]);assert.match((await repository.listNotifications(homeId))[0].title,/Conflito/);});

test('agendamento executa no horário e deduplica o mesmo minuto',async()=>{const {repository,service,homeId,fan}=await setup();const scene=await service.createScene(homeId,{name:'Agenda',actions:[{deviceId:fan.id,controls:{power:true}}]});await service.saveAutomation(homeId,{name:'Às 10h30',sceneId:scene.id,trigger:{type:'schedule',at:'10:30',days:[1]}});const now=new Date('2026-07-13T10:30:10');const first=await service.tick(homeId,now);const second=await service.tick(homeId,now);assert.equal(first[0].status,'succeeded');assert.equal(second[0].status,'duplicate');});
