import test, {after} from 'node:test';
import assert from 'node:assert/strict';
import {connectPostgres} from '../server/infrastructure/postgres.js';
import {PostgresIdentityStore} from '../server/infrastructure/postgres-identity-store.js';
import {PostgresHomeRepository} from '../server/infrastructure/postgres-home-repository.js';
import {TokenService} from '../server/security/token-service.js';
import {AuthService} from '../server/application/auth-service.js';

const pool=await connectPostgres(process.env.DATABASE_URL);
const identity=new PostgresIdentityStore(pool);const repository=new PostgresHomeRepository(pool);
after(async()=>{await pool?.end()});

test('migrations persistem e segregam o domínio residencial no PostgreSQL',{skip:!pool},async()=>{
  const suffix=Date.now();
  const owner=await identity.createUser({email:`postgres-${suffix}@ninho.local`,password:'senha-postgres-segura',displayName:'Postgres QA'});
  let resetUrl;const auth=new AuthService({identity,tokens:new TokenService('q'.repeat(64)),emailSender:{sendPasswordReset:async message=>{resetUrl=message.url;return true}},appUrl:'https://qa.ninho.local'});await auth.requestPasswordReset(owner.email);await auth.resetPassword(new URL(resetUrl).searchParams.get('reset'),'senha-postgres-alterada');assert.ok(await identity.authenticate(owner.email,'senha-postgres-alterada'));
  const home=await identity.createHome({name:'Casa PostgreSQL',ownerId:owner.id});
  const other=await identity.createHome({name:'Outra casa PostgreSQL',ownerId:owner.id});
  const floor=await identity.createFloor({homeId:home.id,name:'Térreo',position:0});
  const room=await identity.createRoom({floorId:floor.id,name:'Sala',position:0});
  const created=await repository.saveDevice(home.id,{name:'Luz persistida',type:'light',roomId:room.id,externalId:`qa-${suffix}`,power:true,brightness:70,color:'#12abef',capabilities:[{code:'color',writable:true}],x:20,y:30});
  assert.equal(created.room,'Sala');assert.equal(created.power,true);assert.equal(created.color,'#12abef');assert.equal(created.capabilities[0].code,'color');assert.equal(created.version,1);
  const failed=await repository.saveDevice(home.id,{name:'Sensor com erro',type:'sensor',roomId:room.id,externalId:`qa-error-${suffix}`,status:'error'});
  assert.equal(failed.status,'error');assert.equal(failed.error,true);assert.equal(failed.online,false);
  const changed=await repository.updateDevice(home.id,created.id,{name:'Luz versionada',version:created.version});assert.equal(changed.version,2);
  assert.equal(await repository.updateDevice(home.id,created.id,{name:'Versão antiga',version:created.version}),false);
  assert.equal(await repository.saveDevice(home.id,{name:'Duplicado',type:'light',roomId:room.id,externalId:`qa-${suffix}`}),false);
  const renamedHome=await identity.updateHome(home.id,{name:'Casa PostgreSQL versionada',version:home.version});assert.equal(renamedHome.version,2);
  assert.equal(await identity.updateHome(home.id,{name:'Versão antiga',version:home.version}),false);
  assert.equal((await repository.listDevices(home.id)).length,2);
  assert.equal((await repository.listDevices(other.id)).length,0);
  const scene=await repository.saveScene(home.id,{name:'Cena PostgreSQL',actions:[{deviceId:created.id,controls:{power:false}}]});
  await repository.saveAutomation(home.id,{name:'Automação PostgreSQL',sceneId:scene.id,trigger:{type:'manual'},conditions:[],enabled:true});
  await repository.addNotification(home.id,{severity:'info',title:'QA',message:'Persistência validada'});
  await repository.addEnergyReading(home.id,{deviceId:created.id,roomId:room.id,kwh:1.25});
  await repository.updateEnergySettings(home.id,{tariff:1.1,currency:'BRL'});
  const plan=await repository.saveFloorplan(home.id,{floors:{[floor.id]:{background:null,rooms:{[room.id]:{x:0,y:0,width:50,height:50}}}}},1);
  const plan2=await repository.saveFloorplan(home.id,{floors:{[floor.id]:{background:null,rooms:{[room.id]:{x:10,y:10,width:40,height:40}}}}},plan.version);
  assert.equal(await repository.saveFloorplan(home.id,plan2.content,plan.version),false);
  const restored=await repository.restoreFloorplan(home.id,plan.version,plan2.version);assert.equal(restored.content.floors[floor.id].rooms[room.id].x,0);
  assert.equal((await repository.listScenes(home.id)).length,1);
  assert.equal((await repository.listAutomations(home.id)).length,1);
  assert.equal((await repository.listNotifications(home.id)).length,1);
  assert.equal((await repository.getEnergy(home.id)).readings.length,1);
  assert.equal((await repository.getFloorplan(home.id)).version,4);
});
