import test from 'node:test';
import assert from 'node:assert/strict';
import { TurnstileVerifier } from '../server/security/turnstile.js';

const response=body=>({ok:true,json:async()=>body});
test('Turnstile permite bypass somente quando explicitamente desativado',async()=>{const verifier=new TurnstileVerifier({required:false});assert.deepEqual(await verifier.verify(''),{success:true,bypassed:true});assert.deepEqual(verifier.publicConfig(),{enabled:false,siteKey:null});});
test('Turnstile valida token, hostname e action no servidor',async()=>{let submitted;const verifier=new TurnstileVerifier({required:true,siteKey:'site-publica',secretKey:'secret-privada',hostname:'ninho.example',fetcher:async(_url,options)=>{submitted=JSON.parse(options.body);return response({success:true,hostname:'ninho.example',action:'login'})}});const result=await verifier.verify('token-unico',{ip:'203.0.113.1',action:'login'});assert.equal(result.success,true);assert.equal(submitted.secret,'secret-privada');assert.equal(submitted.response,'token-unico');assert.ok(submitted.idempotency_key);assert.deepEqual(verifier.publicConfig(),{enabled:true,siteKey:'site-publica'});});
test('Turnstile rejeita token inválido, expirado ou de outro contexto',async()=>{const invalid=new TurnstileVerifier({required:true,siteKey:'site',secretKey:'secret',hostname:'ninho.example',fetcher:async()=>response({success:false,'error-codes':['timeout-or-duplicate']})});await assert.rejects(()=>invalid.verify('replayed',{action:'login'}),error=>error.code==='CAPTCHA_INVALID');const wrongHost=new TurnstileVerifier({required:true,siteKey:'site',secretKey:'secret',hostname:'ninho.example',fetcher:async()=>response({success:true,hostname:'evil.example',action:'login'})});await assert.rejects(()=>wrongHost.verify('token',{action:'login'}),error=>error.code==='CAPTCHA_INVALID');});
test('Turnstile falha fechado quando ativado sem secrets',async()=>{const verifier=new TurnstileVerifier({required:true});await assert.rejects(()=>verifier.verify('token'),error=>error.code==='CAPTCHA_NOT_CONFIGURED'&&error.status===503);});
