import express from 'express';
import crypto from 'node:crypto';
import { AppError } from '../core/app-error.js';
import { validateDevicePatch } from '../domain/device.js';
import { understand } from '../assistant.js';

const invalid=(message)=>new AppError('VALIDATION_ERROR',message,400);
const notFound=(entity)=>new AppError('NOT_FOUND',`${entity} não encontrado.`,404);

export function createHomeDomainRouter({identity,repository,events,controlExternal}){
  const router=express.Router({mergeParams:true});
  router.get('/status',(_req,res)=>res.json({mode:process.env.TUYA_ACCESS_ID?'tuya':'demo',ai:Boolean(process.env.OPENAI_API_KEY),persistence:repository.constructor.name.includes('Postgres')?'postgresql':'memory'}));
  router.get('/events',(req,res)=>events.stream(req,res,event=>event.payload?.homeId===req.params.homeId));
  router.get('/rooms',async(req,res)=>res.json(await identity.listHomeRooms(req.params.homeId)));
  router.post('/rooms',async(req,res,next)=>{try{const name=String(req.body?.name||'').trim();if(!name||name.length>40)throw invalid('Informe um nome de até 40 caracteres.');let floors=await identity.listFloors(req.params.homeId);if(!floors.length)floors=[await identity.createFloor({homeId:req.params.homeId,name:'Térreo',position:0})];const room=await identity.createRoom({floorId:req.body?.floorId||floors[0].id,name,position:(await identity.listHomeRooms(req.params.homeId)).length});if(!room)throw new AppError('ROOM_ALREADY_EXISTS','Esse cômodo já existe.',409);res.status(201).json(room);}catch(error){next(error)}});
  router.patch('/rooms/:id',async(req,res,next)=>{try{const name=String(req.body?.name||'').trim();if(!name||name.length>40)throw invalid('Informe um nome de até 40 caracteres.');const room=await identity.updateRoom(req.params.homeId,req.params.id,{name});if(room===false)throw new AppError('ROOM_ALREADY_EXISTS','Esse cômodo já existe.',409);if(!room)throw notFound('Cômodo');res.json(room);}catch(error){next(error)}});
  router.put('/rooms/order',async(req,res,next)=>{try{if(!Array.isArray(req.body?.ids)||new Set(req.body.ids).size!==req.body.ids.length)throw invalid('Ordem de cômodos inválida.');const rooms=await identity.reorderRooms(req.params.homeId,req.body.ids);if(!rooms)throw invalid('Ordem de cômodos inválida.');res.json(rooms);}catch(error){next(error)}});
  router.delete('/rooms/:id',async(req,res,next)=>{try{const rooms=await identity.listHomeRooms(req.params.homeId);if(rooms.length<=1)throw new AppError('LAST_ROOM','A casa precisa ter pelo menos um cômodo.',409);const devices=await repository.listDevices(req.params.homeId);if(devices.some(item=>item.roomId===req.params.id))throw new AppError('ROOM_NOT_EMPTY','Mova os dispositivos antes de excluir o cômodo.',409);if(!await identity.deleteRoom(req.params.homeId,req.params.id))throw notFound('Cômodo');res.status(204).end();}catch(error){next(error)}});
  router.get('/devices',async(req,res)=>res.json(await repository.listDevices(req.params.homeId)));
  router.post('/devices',async(req,res,next)=>{try{const patch=validateDevicePatch(req.body);if(!patch.name?.trim())throw invalid('Nome do dispositivo é obrigatório.');const room=(await identity.listHomeRooms(req.params.homeId)).find(item=>item.id===req.body.roomId||item.name===patch.room);if(!room)throw invalid('Ambiente inválido.');const created=await repository.saveDevice(req.params.homeId,{...patch,roomId:room.id,room:room.name,id:crypto.randomUUID()});events.publish('device.created',{homeId:req.params.homeId,deviceId:created.id,name:created.name,room:created.room});res.status(201).json(created);}catch(error){next(error)}});
  router.patch('/devices/:id',async(req,res,next)=>{try{const patch=validateDevicePatch(req.body);let room;if(patch.room||req.body.roomId){room=(await identity.listHomeRooms(req.params.homeId)).find(item=>item.id===req.body.roomId||item.name===patch.room);if(!room)throw invalid('Ambiente inválido.');patch.roomId=room.id;patch.room=room.name;}const current=await repository.findDevice(req.params.homeId,req.params.id);if(!current)throw notFound('Dispositivo');const controls=Object.fromEntries(Object.entries(patch).filter(([key])=>['power','brightness','temperature'].includes(key)));if(Object.keys(controls).length&&controlExternal)await controlExternal(current,controls);const updated=await repository.updateDevice(req.params.homeId,req.params.id,patch);events.publish('device.updated',{homeId:req.params.homeId,deviceId:updated.id,name:updated.name,room:updated.room,online:updated.online,power:updated.power});res.json(updated);}catch(error){next(error)}});
  router.delete('/devices/:id',async(req,res,next)=>{try{if(!await repository.deleteDevice(req.params.homeId,req.params.id))throw notFound('Dispositivo');res.status(204).end();}catch(error){next(error)}});
  router.get('/floorplan',async(req,res)=>res.json(await repository.getFloorplan(req.params.homeId)));
  router.put('/floorplan',async(req,res,next)=>{try{if(!req.body||typeof req.body!=='object')throw invalid('Planta inválida.');res.json(await repository.saveFloorplan(req.params.homeId,req.body));}catch(error){next(error)}});
  router.get('/scenes',async(req,res)=>res.json(await repository.listScenes(req.params.homeId)));
  router.post('/scenes',async(req,res,next)=>{try{const name=String(req.body?.name||'').trim();const actions=Array.isArray(req.body?.actions)?req.body.actions:[];if(!name||!actions.length)throw invalid('Informe nome e ações.');res.status(201).json(await repository.saveScene(req.params.homeId,{name,actions}));}catch(error){next(error)}});
  router.patch('/scenes/:id',async(req,res,next)=>{try{const current=(await repository.listScenes(req.params.homeId)).find(item=>item.id===req.params.id);if(!current)throw notFound('Cena');res.json(await repository.saveScene(req.params.homeId,{...current,...req.body,id:current.id}));}catch(error){next(error)}});
  router.delete('/scenes/:id',async(req,res)=>res.status(await repository.deleteScene(req.params.homeId,req.params.id)?204:404).end());
  router.post('/scenes/:id/execute',async(req,res,next)=>{try{const scene=(await repository.listScenes(req.params.homeId)).find(item=>item.id===req.params.id);if(!scene)throw notFound('Cena');const results=await Promise.all(scene.actions.map(async action=>{try{const device=await repository.updateDevice(req.params.homeId,action.deviceId,action.controls);if(!device)throw notFound('Dispositivo');return {deviceId:action.deviceId,status:'succeeded',device};}catch(error){return {deviceId:action.deviceId,status:'failed',error:error.message}}}));const failures=results.filter(item=>item.status==='failed').length;const status=failures===0?'succeeded':failures===results.length?'failed':'partial';await repository.addNotification(req.params.homeId,{severity:status==='succeeded'?'success':'warning',title:`Cena ${scene.name}`,message:`Execução ${status}.`});res.json({executionId:req.body?.executionId||crypto.randomUUID(),sceneId:scene.id,status,results});}catch(error){next(error)}});
  router.get('/automations',async(req,res)=>res.json(await repository.listAutomations(req.params.homeId)));
  router.post('/automations',async(req,res,next)=>{try{const scene=(await repository.listScenes(req.params.homeId)).find(item=>item.id===req.body?.sceneId);if(!scene)throw invalid('Cena inválida.');res.status(201).json(await repository.saveAutomation(req.params.homeId,{name:req.body.name,sceneId:scene.id,trigger:req.body.trigger,conditions:req.body.conditions,enabled:req.body.enabled,lastExecution:null}));}catch(error){next(error)}});
  router.patch('/automations/:id',async(req,res,next)=>{try{const current=(await repository.listAutomations(req.params.homeId)).find(item=>item.id===req.params.id);if(!current)throw notFound('Automação');res.json(await repository.saveAutomation(req.params.homeId,{...current,...req.body,id:current.id}));}catch(error){next(error)}});
  router.delete('/automations/:id',async(req,res)=>res.status(await repository.deleteAutomation(req.params.homeId,req.params.id)?204:404).end());
  router.post('/automations/:id/run',async(req,res,next)=>{try{const automation=(await repository.listAutomations(req.params.homeId)).find(item=>item.id===req.params.id);if(!automation)throw notFound('Automação');if(!automation.enabled)throw new AppError('AUTOMATION_DISABLED','Automação desativada.',409);const scene=(await repository.listScenes(req.params.homeId)).find(item=>item.id===automation.sceneId);const results=await Promise.all(scene.actions.map(action=>repository.updateDevice(req.params.homeId,action.deviceId,action.controls)));const lastExecution={status:'succeeded',executedAt:new Date().toISOString()};await repository.saveAutomation(req.params.homeId,{...automation,lastExecution});res.json({executionId:req.body?.executionId||crypto.randomUUID(),status:'succeeded',results});}catch(error){next(error)}});
  router.get('/notifications',async(req,res)=>res.json(await repository.listNotifications(req.params.homeId)));
  router.patch('/notifications/:id/read',async(req,res,next)=>{try{const value=await repository.readNotification(req.params.homeId,req.params.id);if(!value)throw notFound('Notificação');res.json(value);}catch(error){next(error)}});
  router.get('/energy',async(req,res)=>{const energy=await repository.getEnergy(req.params.homeId);const total=energy.readings.length?energy.readings.reduce((sum,item)=>sum+Number(item.kwh),0):null;res.json({configured:energy.readings.length>0,readings:energy.readings,totalKwh:total,estimatedCost:total!==null&&energy.settings.tariff!==null?total*energy.settings.tariff:null,settings:energy.settings});});
  router.post('/energy/readings',async(req,res,next)=>{try{const kwh=Number(req.body?.kwh);if(!Number.isFinite(kwh)||kwh<0)throw invalid('kWh deve ser positivo.');res.status(201).json(await repository.addEnergyReading(req.params.homeId,{...req.body,kwh}));}catch(error){next(error)}});
  router.patch('/energy/settings',async(req,res,next)=>{try{const tariff=req.body?.tariff===null?null:Number(req.body?.tariff);if(tariff!==null&&(!Number.isFinite(tariff)||tariff<0))throw invalid('Tarifa inválida.');res.json(await repository.updateEnergySettings(req.params.homeId,{tariff,currency:'BRL'}));}catch(error){next(error)}});
  router.post('/assistant',async(req,res,next)=>{try{const text=String(req.body?.text||'').trim();if(!text||text.length>500)throw invalid('Informe um comando de até 500 caracteres.');const devices=await repository.listDevices(req.params.homeId);const action=await understand(text,devices);const targets=devices.filter(device=>action.targetIds.includes(device.id));const changed=await Promise.all(targets.map(device=>repository.updateDevice(req.params.homeId,device.id,action.controls)));res.json({reply:action.reply||`${changed.length} dispositivo(s) atualizado(s).`,changed});}catch(error){next(error)}});
  return router;
}
