import { AppError } from '../core/app-error.js';
import crypto from 'node:crypto';

export class AuthService {
  constructor({identity,tokens,emailSender,appUrl=process.env.APP_URL||'http://localhost:5173'}){this.identity=identity;this.tokens=tokens;this.emailSender=emailSender;this.appUrl=appUrl.replace(/\/$/,'');}
  issue(user){const publicUser={id:user.id,email:user.email,displayName:user.displayName,status:user.status};return {accessToken:this.tokens.sign({sub:user.id,email:user.email,ver:user.sessionVersion||0},15*60,'access'),refreshToken:this.tokens.sign({sub:user.id,ver:user.sessionVersion||0},7*24*60*60,'refresh'),expiresIn:900,user:publicUser};}
  async register(input){if(!input.email||!input.password||input.password.length<10||!input.displayName)throw new AppError('VALIDATION_ERROR','E-mail, nome e senha com ao menos 10 caracteres são obrigatórios.',400);const user=await this.identity.createUser(input);if(!user)throw new AppError('EMAIL_ALREADY_EXISTS','E-mail já cadastrado.',409);await this.identity.record({type:'USER_REGISTERED',actorId:user.id,result:'succeeded'});return this.issue(user);}
  async login(email,password){const user=await this.identity.authenticate(email,password);if(!user){await this.identity.record({type:'LOGIN_FAILED',result:'failed'});throw new AppError('INVALID_CREDENTIALS','E-mail ou senha inválidos.',401);}await this.identity.record({type:'LOGIN_SUCCEEDED',actorId:user.id,result:'succeeded'});return this.issue(user);}
  async refresh(token){const payload=this.tokens.verify(token,'refresh');if(await this.identity.isRevoked(payload.jti))throw new AppError('INVALID_SESSION','Sessão revogada.',401);await this.identity.revoke(payload.jti);const user=await this.identity.findUser(payload.sub);if(!user||user.sessionVersion!==payload.ver)throw new AppError('INVALID_SESSION','Sessão inválida.',401);return this.issue(user);}
  async logout(refreshToken){if(!refreshToken)return;try{const payload=this.tokens.verify(refreshToken,'refresh');await this.identity.revoke(payload.jti)}catch{}}
  async requestPasswordReset(email){const user=await this.identity.findUserByEmail(email);if(!user)return;const token=crypto.randomBytes(32).toString('base64url');const tokenHash=crypto.createHash('sha256').update(token).digest('hex');await this.identity.savePasswordReset({userId:user.id,tokenHash,expiresAt:new Date(Date.now()+30*60*1000).toISOString()});let delivered=false;try{delivered=Boolean(await this.emailSender?.sendPasswordReset({email:user.email,displayName:user.displayName,url:`${this.appUrl}/?reset=${encodeURIComponent(token)}`}))}catch{}await this.identity.record({type:'PASSWORD_RESET_REQUESTED',actorId:user.id,result:delivered?'delivered':'delivery_unavailable'});}
  async resetPassword(token,password){if(!token||String(token).length>128||!password||password.length<10)throw new AppError('VALIDATION_ERROR','Token e senha com ao menos 10 caracteres são obrigatórios.',400);const tokenHash=crypto.createHash('sha256').update(String(token)).digest('hex');const userId=await this.identity.consumePasswordReset(tokenHash);if(!userId)throw new AppError('INVALID_RESET_TOKEN','Link inválido, expirado ou já utilizado.',400);await this.identity.updatePassword(userId,password);await this.identity.record({type:'PASSWORD_RESET_COMPLETED',actorId:userId,result:'succeeded'});}
}
