import { useEffect, useState } from 'react';
import { Bell, Check, Gauge, Play, Plus, RefreshCw, Sparkles, Trash2, Workflow } from 'lucide-react';

const API='/api';
async function api(path,options){const response=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json'},...options});const data=response.status===204?null:await response.json();if(!response.ok)throw new Error(data?.error||'Não foi possível concluir a operação.');return data;}

export function AutomationCenter({devices,notify}) {
  const [tab,setTab]=useState('scenes');const [scenes,setScenes]=useState([]);const [automations,setAutomations]=useState([]);const [notifications,setNotifications]=useState([]);const [energy,setEnergy]=useState(null);const [busy,setBusy]=useState(false);
  const [sceneForm,setSceneForm]=useState({name:'',deviceId:'',power:true});const [automationForm,setAutomationForm]=useState({name:'',sceneId:''});
  async function load(){const [s,a,n,e]=await Promise.all([api('/scenes'),api('/automations'),api('/notifications'),api('/energy')]);setScenes(s);setAutomations(a);setNotifications(n);setEnergy(e);}
  useEffect(()=>{load().catch(error=>notify(error.message,'error'));},[]);
  async function createScene(event){event.preventDefault();setBusy(true);try{const created=await api('/scenes',{method:'POST',body:JSON.stringify({name:sceneForm.name,actions:[{deviceId:sceneForm.deviceId,controls:{power:sceneForm.power}}]})});setScenes(items=>[...items,created]);setSceneForm({name:'',deviceId:'',power:true});notify('Cena criada.','success');}catch(error){notify(error.message,'error');}finally{setBusy(false)}}
  async function execute(scene){setBusy(true);try{const result=await api(`/scenes/${scene.id}/execute`,{method:'POST',body:JSON.stringify({executionId:crypto.randomUUID()})});notify(result.status==='succeeded'?'Cena executada.':`Execução ${result.status}.`,result.status==='succeeded'?'success':'error');await load();}catch(error){notify(error.message,'error');}finally{setBusy(false)}}
  async function createAutomation(event){event.preventDefault();try{const created=await api('/automations',{method:'POST',body:JSON.stringify({...automationForm,trigger:{type:'manual'}})});setAutomations(items=>[...items,created]);setAutomationForm({name:'',sceneId:''});notify('Automação criada.','success');}catch(error){notify(error.message,'error')}}
  async function remove(kind,id){try{await api(`/${kind}/${id}`,{method:'DELETE'});await load();notify('Item removido.','success');}catch(error){notify(error.message,'error')}}
  async function toggle(item){try{const changed=await api(`/automations/${item.id}`,{method:'PATCH',body:JSON.stringify({enabled:!item.enabled})});setAutomations(items=>items.map(value=>value.id===item.id?changed:value));}catch(error){notify(error.message,'error')}}
  const tabs=[['scenes','Cenas',Sparkles],['automations','Automações',Workflow],['notifications','Alertas',Bell],['energy','Energia',Gauge]];
  return <section className="automation-center"><div className="center-tabs" role="tablist">{tabs.map(([id,label,Icon])=><button role="tab" aria-selected={tab===id} className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon/>{label}{id==='notifications'&&notifications.some(item=>!item.readAt)&&<i/>}</button>)}</div>
    {tab==='scenes'&&<div className="center-layout"><div><div className="section-title"><div><h2>Cenas</h2><p>Execute várias ações de uma só vez.</p></div></div><div className="routine-list">{scenes.length?scenes.map(scene=><article key={scene.id}><span><Sparkles/></span><div><b>{scene.name}</b><small>{scene.actions.length} ação(ões)</small></div><button disabled={busy} aria-label={`Executar ${scene.name}`} onClick={()=>execute(scene)}><Play/></button><button className="danger" aria-label={`Excluir ${scene.name}`} onClick={()=>remove('scenes',scene.id)}><Trash2/></button></article>):<Empty text="Nenhuma cena criada."/>}</div></div><form className="routine-form" onSubmit={createScene}><h3><Plus/> Nova cena</h3><label>Nome<input required value={sceneForm.name} onChange={e=>setSceneForm({...sceneForm,name:e.target.value})} placeholder="Ex: Hora de dormir"/></label><label>Dispositivo<select required value={sceneForm.deviceId} onChange={e=>setSceneForm({...sceneForm,deviceId:e.target.value})}><option value="">Selecione</option>{devices.map(device=><option key={device.id} value={device.id}>{device.name}</option>)}</select></label><label>Ação<select value={String(sceneForm.power)} onChange={e=>setSceneForm({...sceneForm,power:e.target.value==='true'})}><option value="true">Ligar</option><option value="false">Desligar</option></select></label><button disabled={busy} className="primary">Criar cena</button></form></div>}
    {tab==='automations'&&<div className="center-layout"><div><div className="section-title"><div><h2>Automações</h2><p>Regras com gatilhos, condições e ações.</p></div></div><div className="routine-list">{automations.length?automations.map(item=><article key={item.id}><span><Workflow/></span><div><b>{item.name}</b><small>{item.lastExecution?`Última: ${item.lastExecution.status}`:'Nunca executada'}</small></div><button className={`mini-switch ${item.enabled?'on':''}`} aria-label={`${item.enabled?'Desativar':'Ativar'} ${item.name}`} onClick={()=>toggle(item)}><i/></button><button disabled={!item.enabled} aria-label={`Testar ${item.name}`} onClick={async()=>{try{await api(`/automations/${item.id}/run`,{method:'POST',body:JSON.stringify({executionId:crypto.randomUUID()})});notify('Automação testada.','success');await load();}catch(error){notify(error.message,'error')}}}><Play/></button><button className="danger" onClick={()=>remove('automations',item.id)}><Trash2/></button></article>):<Empty text="Nenhuma automação criada."/>}</div></div><form className="routine-form" onSubmit={createAutomation}><h3><Plus/> Nova automação</h3><label>Nome<input required value={automationForm.name} onChange={e=>setAutomationForm({...automationForm,name:e.target.value})}/></label><label>Cena<select required value={automationForm.sceneId} onChange={e=>setAutomationForm({...automationForm,sceneId:e.target.value})}><option value="">Selecione</option>{scenes.map(scene=><option key={scene.id} value={scene.id}>{scene.name}</option>)}</select></label><p>Gatilho inicial: execução manual. Gatilhos por horário e sensores serão habilitados ao integrar o provedor.</p><button className="primary">Criar automação</button></form></div>}
    {tab==='notifications'&&<div><div className="section-title"><div><h2>Central de notificações</h2><p>Resultados importantes das rotinas da casa.</p></div><button className="secondary" onClick={load}><RefreshCw/> Atualizar</button></div><div className="notification-list">{notifications.length?notifications.map(item=><article className={item.readAt?'read':''} key={item.id}><span className={item.severity}><Bell/></span><div><b>{item.title}</b><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleString('pt-BR')}</small></div>{!item.readAt&&<button onClick={async()=>{await api(`/notifications/${item.id}/read`,{method:'PATCH'});await load();}}><Check/> Marcar como lida</button>}</article>):<Empty text="Nenhuma notificação."/>}</div></div>}
    {tab==='energy'&&<Energy energy={energy} reload={load} notify={notify}/>} 
  </section>;
}
function Empty({text}){return <div className="routine-empty">{text}</div>}
function Energy({energy,reload,notify}){const [tariff,setTariff]=useState('');if(!energy)return <Empty text="Carregando dados de energia..."/>;return <div className="energy-view"><div className="section-title"><div><h2>Energia</h2><p>Consumo registrado por medidores integrados.</p></div></div><div className="energy-cards"><article><small>Consumo acumulado</small><b>{energy.totalKwh===null?'Não configurado':`${energy.totalKwh.toFixed(2)} kWh`}</b></article><article><small>Custo estimado</small><b>{energy.estimatedCost===null?'Não disponível':energy.estimatedCost.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b></article><article><small>Leituras reais</small><b>{energy.readings.length||'Nenhuma'}</b></article></div>{!energy.configured&&<div className="energy-empty"><Gauge/><h3>Nenhum medidor de energia vinculado</h3><p>O sistema não considera ausência de dados como consumo zero. Vincule um medidor compatível para começar.</p></div>}<form className="tariff-form" onSubmit={async e=>{e.preventDefault();try{await api('/energy/settings',{method:'PATCH',body:JSON.stringify({tariff:Number(tariff)})});notify('Tarifa atualizada.','success');await reload();}catch(error){notify(error.message,'error')}}}><label>Tarifa por kWh (R$)<input type="number" min="0" step="0.01" required value={tariff} onChange={e=>setTariff(e.target.value)} placeholder={energy.settings.tariff??'Ex: 0,95'}/></label><button className="primary">Salvar tarifa</button></form></div>}
