import {useEffect,useMemo,useRef,useState} from 'react';
import {Camera,DoorOpen,Expand,FileImage,Flame,Grid3X3,History,Lamp,Layers3,LocateFixed,Maximize2,Minus,Move,Plus,PlugZap,Save,ShieldCheck,Thermometer,Trash2,Tv,Upload,ZoomIn,ZoomOut} from 'lucide-react';
import {defaultRoomGeometry,deviceLayerMetric,moveRoomGeometry,normalizeFloorplanPoint,normalizeZoom,pinchZoom,resizeRoomGeometry} from '../domain/floorplan.js';
import {deviceStatusLabel,deviceVisualStatus} from '../domain/device-command.js';

const deviceIcons={light:Lamp,ac:Thermometer,tv:Tv,plug:PlugZap,camera:Camera,lock:ShieldCheck};
const layerOptions=[['rooms','Cômodos',DoorOpen],['devices','Dispositivos',PlugZap],['labels','Nomes',FileImage],['grid','Grade',Grid3X3],['temperature','Temperatura',Thermometer],['energy','Energia',Flame],['cameras','Câmeras',Camera],['security','Segurança',ShieldCheck]];
const clone=value=>structuredClone(value);
function DeviceGlyph({type}){const Icon=deviceIcons[type]||PlugZap;return <Icon/>;}
function savedViews(){try{return JSON.parse(sessionStorage.getItem('ninho-floorplan-views')||'{}');}catch{return {};}}

export function FloorplanEditor({mode,devices,rooms,update,select,add,manage,apiBase,notify,onDirtyChange}){
  const [editing,setEditing]=useState(false);const [floors,setFloors]=useState([]);const [floorplan,setFloorplan]=useState({floors:{}});const [version,setVersion]=useState(1);const [versions,setVersions]=useState([]);const [historyOpen,setHistoryOpen]=useState(false);const [activeFloor,setActiveFloor]=useState('');
  const [draft,setDraft]=useState(null);const [deviceDraft,setDeviceDraft]=useState({});const [dirty,setDirty]=useState(false);const [saving,setSaving]=useState(false);const [floorState,setFloorState]=useState({loading:true,error:''});
  const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:0,y:0});const [layers,setLayers]=useState({rooms:true,devices:true,labels:true,grid:true,temperature:false,energy:false,cameras:false,security:false});
  const [layersOpen,setLayersOpen]=useState(false);const [selectedRoom,setSelectedRoom]=useState(null);const [fullScreen,setFullScreen]=useState(false);const [uploading,setUploading]=useState(false);
  const gesture=useRef(null);const pointers=useRef(new Map());const viewport=useRef(null);const shell=useRef(null);const fileInput=useRef(null);
  const floorRooms=useMemo(()=>rooms.filter(room=>room.floorId===activeFloor),[rooms,activeFloor]);const roomIds=useMemo(()=>new Set(floorRooms.map(room=>room.id)),[floorRooms]);const floorDevices=useMemo(()=>devices.filter(device=>roomIds.has(device.roomId)),[devices,roomIds]);
  const content=draft||floorplan;const floorContent=content.floors?.[activeFloor]||{};const background=floorContent.background;

  async function loadVersions(){const response=await fetch(`${apiBase}/floorplan/versions`);if(response.ok)setVersions(await response.json());}
  useEffect(()=>{setFloorState({loading:true,error:''});Promise.all([fetch(`${apiBase}/floors`).then(r=>r.ok?r.json():Promise.reject()),fetch(`${apiBase}/floorplan`).then(r=>r.ok?r.json():Promise.reject())]).then(([items,plan])=>{setFloors(items);setFloorplan(plan.content?.floors?plan.content:{floors:{}});setVersion(plan.version||1);setActiveFloor(items[0]?.id||'');setFloorState({loading:false,error:''});loadVersions();}).catch(()=>{setFloorState({loading:false,error:'Não foi possível carregar a planta.'});notify('Não foi possível carregar a planta.','error')});},[apiBase]);
  useEffect(()=>{onDirtyChange?.(dirty);const beforeUnload=event=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);return()=>window.removeEventListener('beforeunload',beforeUnload);},[dirty,onDirtyChange]);
  useEffect(()=>{const handler=()=>setFullScreen(document.fullscreenElement===shell.current);document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler);},[]);
  useEffect(()=>{if(!activeFloor)return;const saved=savedViews()[activeFloor];setZoom(saved?.zoom||1);setPan(saved?.pan||{x:0,y:0});setSelectedRoom(null);},[activeFloor]);

  function persist(nextZoom,nextPan){if(!activeFloor)return;const values=savedViews();values[activeFloor]={zoom:nextZoom,pan:nextPan};sessionStorage.setItem('ninho-floorplan-views',JSON.stringify(values));}
  function changeZoom(next){const value=normalizeZoom(next);setZoom(value);persist(value,pan);}function resetView(){const next={x:0,y:0};setZoom(1);setPan(next);persist(1,next);}
  function beginDraft(){setDraft(clone(floorplan));setDeviceDraft({});setDirty(false);setEditing(true);}
  function discard(){setDraft(null);setDeviceDraft({});setDirty(false);setEditing(false);}
  function finishEditing(){if(dirty&&!window.confirm('Descartar as alterações não salvas?'))return;discard();}
  function markDraft(mutator){setDraft(current=>{const next=clone(current||floorplan);mutator(next);return next;});setDirty(true);}
  function roomGeometry(room,index){return floorContent.rooms?.[room.id]||defaultRoomGeometry(index,floorRooms.length);}
  function switchFloor(id){if(dirty&&!window.confirm('Trocar de piso e descartar as alterações não salvas?'))return;if(dirty)discard();setActiveFloor(id);}
  function startPan(event){if(event.target.closest('.point')||event.target.closest('.room'))return;pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});try{event.currentTarget.setPointerCapture(event.pointerId);}catch{}if(pointers.current.size===2){const [a,b]=[...pointers.current.values()];gesture.current={kind:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),zoom};return;}gesture.current={kind:'pan',pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,pan};}
  function startDevice(event,device){if(!editing)return;event.stopPropagation();gesture.current={kind:'device',pointerId:event.pointerId,device};try{event.currentTarget.setPointerCapture(event.pointerId);}catch{}}
  function startRoom(event,room,geometry,kind='room'){if(!editing)return;event.stopPropagation();gesture.current={kind,pointerId:event.pointerId,room,geometry,startX:event.clientX,startY:event.clientY};try{event.currentTarget.setPointerCapture(event.pointerId);}catch{}}
  function move(event){if(pointers.current.has(event.pointerId))pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});const active=gesture.current;if(!active)return;if(active.kind==='pinch'&&pointers.current.size>=2){const [a,b]=[...pointers.current.values()];const value=pinchZoom(active.zoom,active.distance,Math.hypot(a.x-b.x,a.y-b.y));active.latestZoom=value;setZoom(value);return;}if(active.kind==='pan'&&active.pointerId===event.pointerId){active.latestPan={x:active.pan.x+event.clientX-active.startX,y:active.pan.y+event.clientY-active.startY};setPan(active.latestPan);return;}if(active.kind==='device'){const rect=viewport.current.getBoundingClientRect();active.position=normalizeFloorplanPoint({clientX:event.clientX,clientY:event.clientY,rect,pan,zoom});setDeviceDraft(value=>({...value,[active.device.id]:active.position}));setDirty(true);return;}if(active.kind==='room'||active.kind==='resize'){const rect=viewport.current.getBoundingClientRect();const dx=(event.clientX-active.startX)/zoom/rect.width*100;const dy=(event.clientY-active.startY)/zoom/rect.height*100;const geometry=active.kind==='resize'?resizeRoomGeometry(active.geometry,dx,dy):moveRoomGeometry(active.geometry,dx,dy);markDraft(next=>{next.floors[activeFloor]??={background:null,rooms:{}};next.floors[activeFloor].rooms??={};next.floors[activeFloor].rooms[active.room.id]=geometry;});}}
  function end(event){pointers.current.delete(event.pointerId);const active=gesture.current;if(!active)return;if(active.kind==='pinch'){persist(active.latestZoom||zoom,pan);gesture.current=null;return;}if(active.pointerId!==event.pointerId)return;if(active.kind==='pan')persist(zoom,active.latestPan||pan);gesture.current=null;}
  function toggleLayer(key){setLayers(value=>({...value,[key]:!value[key]}));}
  async function toggleFullScreen(){if(!document.fullscreenElement){if(!shell.current?.requestFullscreen)return notify('Tela cheia não está disponível neste navegador.','info');await shell.current.requestFullscreen();}else await document.exitFullscreen();}
  async function saveContent(next,expected=version){const response=await fetch(`${apiBase}/floorplan`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:expected,content:next})});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);setFloorplan(result.content);setVersion(result.version);await loadVersions();return result;}
  async function saveDraft(){setSaving(true);try{for(const [id,position] of Object.entries(deviceDraft)){const changed=await update(id,position);if(!changed)throw new Error('Não foi possível salvar a posição de um dispositivo.');}await saveContent(draft||floorplan);setDraft(null);setDeviceDraft({});setDirty(false);setEditing(false);notify('Nova versão da planta salva.','success');}catch(error){notify(error.message,'error');}finally{setSaving(false);}}
  async function restore(target){if(!window.confirm(`Restaurar a versão ${target}? A planta atual será preservada no histórico.`))return;setSaving(true);try{const response=await fetch(`${apiBase}/floorplan/versions/${target}/restore`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version})});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);setFloorplan(result.content);setVersion(result.version);discard();await loadVersions();notify(`Versão ${target} restaurada.`,'success');}catch(error){notify(error.message,'error');}finally{setSaving(false);}}
  function upload(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>2*1024*1024)return notify('A planta deve ter no máximo 2 MB.','error');if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(file.type))return notify('Use uma imagem PNG, JPEG, WebP ou SVG.','error');const reader=new FileReader();reader.onerror=()=>notify('Não foi possível ler o arquivo.','error');reader.onload=async()=>{setUploading(true);try{const next=clone(floorplan);next.floors??={};next.floors[activeFloor]={...(next.floors[activeFloor]||{}),background:{name:file.name,mime:file.type,dataUrl:reader.result},rooms:next.floors[activeFloor]?.rooms||{}};await saveContent(next);notify('Planta do piso atualizada.','success');}catch(error){notify(error.message,'error');}finally{setUploading(false)}};reader.readAsDataURL(file);}
  async function removeBackground(){setUploading(true);try{const next=clone(floorplan);next.floors[activeFloor]={...(next.floors[activeFloor]||{}),background:null,rooms:next.floors[activeFloor]?.rooms||{}};await saveContent(next);notify('Imagem da planta removida.','success');}catch(error){notify(error.message,'error');}finally{setUploading(false);}}

  return <section className="floorplan-editor"><div className="plant-toolbar"><div><b>{editing?'Modo edição':'Modo visualização'}</b><p>{editing?'Ajuste cômodos e pontos; comandos estão bloqueados.':'Navegue pela planta e ative visualizações operacionais.'}</p>{dirty&&<span className="unsaved-indicator" role="status">Alterações não salvas</span>}</div><div className="toolbar-actions">{editing?<><button className="secondary" onClick={finishEditing}>Cancelar</button><button className="primary" disabled={!dirty||saving} onClick={saveDraft}><Save/>{saving?'Salvando...':'Salvar versão'}</button></>:<button className="secondary" onClick={beginDraft}><Move/> Editar planta</button>}<button className="secondary" onClick={()=>{setHistoryOpen(value=>!value);loadVersions();}}><History/> Versões</button><button className="secondary" onClick={manage}><DoorOpen/> Cômodos</button><button className="primary" disabled={editing} onClick={add}><Plus/> {mode==='tuya'?'Vincular':'Adicionar'}</button></div></div>
    <div className="floor-tabs" role="tablist" aria-label="Pisos da residência">{floors.map(floor=><button role="tab" aria-selected={activeFloor===floor.id} className={activeFloor===floor.id?'active':''} key={floor.id} onClick={()=>switchFloor(floor.id)}>{floor.name}</button>)}</div>
    <div ref={shell} className={`floorplan-shell ${fullScreen?'fullscreen':''}`}><div className="floorplan-controls" aria-label="Controles da planta"><button aria-label="Aumentar zoom" onClick={()=>changeZoom(zoom+.2)}><ZoomIn/></button><button aria-label="Diminuir zoom" onClick={()=>changeZoom(zoom-.2)}><ZoomOut/></button><button aria-label="Centralizar planta" onClick={resetView}><LocateFixed/></button><button aria-label={fullScreen?'Sair da tela cheia':'Abrir em tela cheia'} onClick={toggleFullScreen}>{fullScreen?<Minus/>:<Maximize2/>}</button><button aria-label="Configurar camadas" className={layersOpen?'active':''} onClick={()=>setLayersOpen(value=>!value)}><Layers3/></button><output aria-live="polite">{Math.round(zoom*100)}%</output></div>
      <div className="floorplan-upload"><input ref={fileInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={upload}/><button disabled={!activeFloor||uploading||editing} className="secondary" onClick={()=>fileInput.current?.click()}>{uploading?<Expand className="spin"/>:<Upload/>}{background?'Trocar planta':'Enviar planta'}</button>{background&&<button disabled={uploading||editing} className="secondary danger" aria-label="Remover imagem da planta" onClick={removeBackground}><Trash2/></button>}</div>
      {layersOpen&&<div className="layer-panel"><b>Camadas</b>{layerOptions.map(([key,label,Icon])=><label key={key}><input type="checkbox" checked={layers[key]} onChange={()=>toggleLayer(key)}/><Icon/>{label}</label>)}</div>}
      {historyOpen&&<aside className="version-panel" aria-label="Histórico da planta"><b>Versões salvas</b>{versions.length?versions.map(item=><div key={item.version}><span><strong>v{item.version}</strong><small>{item.createdAt?new Date(item.createdAt).toLocaleString('pt-BR'):'Versão atual'}</small></span><button disabled={item.version===version||saving} onClick={()=>restore(item.version)}>Restaurar</button></div>):<small>Nenhuma versão anterior.</small>}</aside>}
      <div ref={viewport} className={`floorplan-viewport ${editing?'editing':''}`} onPointerDown={startPan} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onWheel={event=>{event.preventDefault();changeZoom(zoom+(event.deltaY<0?.12:-.12));}}><div className={`floorplan ${layers.grid?'show-grid':''} ${background?'has-background':''}`} style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
        {floorState.loading&&<div className="floorplan-fetch-state" role="status"><Expand className="spin"/><b>Carregando planta...</b></div>}{floorState.error&&<div className="floorplan-fetch-state error" role="alert"><FileImage/><b>{floorState.error}</b></div>}{background&&<img className="floorplan-background" src={background.dataUrl} alt={`Planta ${background.name}`}/>} {!floorState.loading&&!floorState.error&&!background&&<div className="floorplan-placeholder"><FileImage/><b>Nenhuma imagem neste piso</b><small>Use “Enviar planta” para adicionar um fundo.</small></div>}
        {layers.rooms&&floorRooms.map((room,index)=>{const geometry=roomGeometry(room,index);return <button type="button" className={`room geometric room-${index%8} ${selectedRoom===room.id?'selected':''}`} style={{left:`${geometry.x}%`,top:`${geometry.y}%`,width:`${geometry.width}%`,height:`${geometry.height}%`}} key={room.id} onPointerDown={event=>startRoom(event,room,geometry)} onClick={event=>{event.stopPropagation();setSelectedRoom(room.id)}}><div className="room-label">{layers.labels&&<><b>{room.name.toUpperCase()}</b><small>AMBIENTE {index+1}</small></>}</div>{editing&&<i className="room-resize" role="presentation" onPointerDown={event=>startRoom(event,room,geometry,'resize')}/>}</button>})}
        {layers.devices&&floorDevices.map(device=>{const visual=deviceVisualStatus(device);const position=deviceDraft[device.id]||device;const metrics=['temperature','energy','cameras','security'].map(layer=>layers[layer]&&deviceLayerMetric(device,layer)).filter(Boolean);const hiddenByFocus=(layers.cameras&&device.type!=='camera')||(layers.security&&!['lock','cover','camera'].includes(device.type));return <button key={device.id} data-status={visual} className={`point ${visual} ${editing?'movable':''} ${hiddenByFocus?'layer-muted':''}`} style={{left:`${position.x??50}%`,top:`${position.y??50}%`}} onPointerDown={event=>startDevice(event,device)} onClick={event=>{event.stopPropagation();if(!editing)select(device)}} aria-label={`${device.name}, ${deviceStatusLabel(device)}`} aria-busy={visual==='pending'} aria-disabled={editing} title={editing?`Mover ${device.name}`:`Controlar ${device.name}`}><DeviceGlyph type={device.type}/><i className="device-point-status" aria-hidden="true"/>{layers.labels&&<span>{device.name} · {deviceStatusLabel(device)}</span>}{metrics.map(metric=><em key={metric}>{metric}</em>)}</button>})}
      </div></div><div className="floorplan-legend"><span className="on">Ligado</span><span className="off">Desligado</span><span className="offline">Offline</span><span className="error">Erro</span><small><Minus/> Arraste ou use dois dedos para navegar</small></div>{selectedRoom&&<div className="room-context" role="status"><DoorOpen/><span><small>Ambiente selecionado</small><b>{floorRooms.find(room=>room.id===selectedRoom)?.name}</b></span><button aria-label="Limpar seleção do ambiente" onClick={()=>setSelectedRoom(null)}>×</button></div>}</div>
  </section>;
}
